### ISSUE TITLE
Raspberry Pi Pico Panic in rot service ipc

### ISSUE THREAD

**Issue by alexandruradovici** [tock/tock#3183]
The panic seems to be related to the `rot13_callback`. If the whole function is commented, there is no panic. If only its last line is commented, it panics.

```
␀RP2040 Revision 1 ASIC
Initia
panicked at 'Process org.tockos.examples.rot13 had a fault', kernel/src/process_standard.rs:333:17
        Kernel version tock-registers-v0.8-33-ge24d4c9df

---| No debug queue found. You can set it with the DebugQueue component.

---| Cortex-M Fault Status |---
No Cortex-M faults detected.

---| App Status |---
𝐀𝐩𝐩: org.tockos.examples.rot13   -   [Faulted]
 Events Queued: 0   Syscall Count: 8   Dropped Upcall Count: 0
 Restart Count: 0
 Last Syscall: Yield { which: 1, address: 0x0 }
 Completion Code: None


 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x20006000═╪══════════════════════════════════════════╝
             │ Grant Ptrs       56
             │ Upcalls         360
             │ Process         880
  0x20005AF0 ┼───────────────────────────────────────────
             │ ▼ Grant          76
  0x20005AA4 ┼───────────────────────────────────────────
             │ Unused
  0x200049F4 ┼───────────────────────────────────────────
             │ ▲ Heap            0 |   4272               S
  0x200049F4 ┼─────────────────────────────────────────── R
             │ Data            500 |    500               A
  0x20004800 ┼─────────────────────────────────────────── M
             │ ▼ Stack         184 |   2048          
  0x20004748 ┼───────────────────────────────────────────
             │ Unused
  0x20004000 ┴───────────────────────────────────────────
             .....
  0x10020800 ┬─────────────────────────────────────────── F
             │ App Flash      1976                        L
  0x10020048 ┼─────────────────────────────────────────── A
             │ Protected        72                        S
  0x10020000 ┴─────────────────────────────────────────── H

  R0 : 0x00010000    R6 : 0x00000000
  R1 : 0x00000003    R7 : 0x00000000
  R2 : 0x00000001    R8 : 0x200047A8
  R3 : 0x00000000    R10: 0x0000000C
  R4 : 0x00000000    R11: 0x0000001A
  R5 : 0x20004800    R12: 0x0000000A
  R9 : 0x00000001 (Static Base Register)
  SP : 0x20004778 (Process Stack Pointer)
  LR : 0x1002026F
  PC : 0x100203A2
 YPC : 0x1002035A

 APSR: N 0 Z 0 C 0 V 0 Q 0
       GE 0 0 0 0
 EPSR: ICI.IT 0x00
       ThumbBit true 

 Total number of grant regions defined: 7
  Grant  0 : --          Grant  3 : --          Grant  6 0x10000: 0x20005aa4
  Grant  1 : --          Grant  4 : --        
  Grant  2 : --          Grant  5 : --        

 Cortex-M MPU
  Region 0: [0x20004000:0x20006000], length: 8192 bytes; ReadWrite (0x3)
    Sub-region 0: [0x20004000:0x20004400], Enabled
    Sub-region 1: [0x20004400:0x20004800], Enabled
    Sub-region 2: [0x20004800:0x20004C00], Enabled
    Sub-region 3: [0x20004C00:0x20005000], Disabled
    Sub-region 4: [0x20005000:0x20005400], Disabled
    Sub-region 5: [0x20005400:0x20005800], Disabled
    Sub-region 6: [0x20005800:0x20005C00], Disabled
    Sub-region 7: [0x20005C00:0x20006000], Disabled
  Region 1: [0x10020000:0x10020800], length: 2048 bytes; UnprivilegedReadOnly (0x2)
    Sub-region 0: [0x10020000:0x10020100], Enabled
    Sub-region 1: [0x10020100:0x10020200], Enabled
    Sub-region 2: [0x10020200:0x10020300], Enabled
    Sub-region 3: [0x10020300:0x10020400], Enabled
    Sub-region 4: [0x10020400:0x10020500], Enabled
    Sub-region 5: [0x10020500:0x10020600], Enabled
    Sub-region 6: [0x10020600:0x10020700], Enabled
    Sub-region 7: [0x10020700:0x10020800], Enabled
  Region 2: Unused
  Region 3: Unused
  Region 4: Unused
  Region 5: Unused
  Region 6: Unused
  Region 7: Unused

To debug, run `make debug RAM_START=0x20004000 FLASH_INIT=0x10020071`
in the app's folder and open the .lst file.

𝐀𝐩𝐩: rot13_client   -   [Yielded]
 Events Queued: 0   Syscall Count: 10   Dropped Upcall Count: 0
 Restart Count: 0
 Last Syscall: Yield { which: 1, address: 0x0 }
 Completion Code: None


 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x20008000═╪══════════════════════════════════════════╝
             │ Grant Ptrs       56
             │ Upcalls         360
             │ Process         880
  0x20007AF0 ┼───────────────────────────────────────────
             │ ▼ Grant          76
  0x20007AA4 ┼───────────────────────────────────────────
             │ Unused
  0x20006AE8 ┼───────────────────────────────────────────
             │ ▲ Heap            0 |   4028               S
  0x20006AE8 ┼─────────────────────────────────────────── R
             │ Data            744 |    744               A
  0x20006800 ┼─────────────────────────────────────────── M
             │ ▼ Stack         152 |   2048          
  0x20006768 ┼───────────────────────────────────────────
             │ Unused
  0x20006000 ┴───────────────────────────────────────────
             .....
  0x10022800 ┬─────────────────────────────────────────── F
             │ App Flash      8136                        L
  0x10020838 ┼─────────────────────────────────────────── A
             │ Protected        56                        S
  0x10020800 ┴─────────────────────────────────────────── H

  R0 : 0x00000001    R6 : 0x00000000
  R1 : 0x00000000    R7 : 0x00000000
  R2 : 0x00000000    R8 : 0x10020838
  R3 : 0x20006800    R10: 0x1002251C
  R4 : 0x00000000    R11: 0x80000000
  R5 : 0x20006800    R12: 0xE9696B39
  R9 : 0x20006000 (Static Base Register)
  SP : 0x200067C0 (Process Stack Pointer)
  LR : 0x20006800
  PC : 0x10020DA2
 YPC : 0x10020DA2

 APSR: N 0 Z 0 C 1 V 0 Q 0
       GE 0 0 0 0
 EPSR: ICI.IT 0x00
       ThumbBit true 

 Total number of grant regions defined: 7
  Grant  0 : --          Grant  3 : --          Grant  6 0x10000: 0x20007aa4
  Grant  1 : --          Grant  4 : --        
  Grant  2 : --          Grant  5 : --        

 Cortex-M MPU
  Region 0: [0x20006000:0x20008000], length: 8192 bytes; ReadWrite (0x3)
    Sub-region 0: [0x20006000:0x20006400], Enabled
    Sub-region 1: [0x20006400:0x20006800], Enabled
    Sub-region 2: [0x20006800:0x20006C00], Enabled
    Sub-region 3: [0x20006C00:0x20007000], Disabled
    Sub-region 4: [0x20007000:0x20007400], Disabled
    Sub-region 5: [0x20007400:0x20007800], Disabled
    Sub-region 6: [0x20007800:0x20007C00], Disabled
    Sub-region 7: [0x20007C00:0x20008000], Disabled
  Region 1: [0x10020800:0x10022800], length: 8192 bytes; UnprivilegedReadOnly (0x2)
    Sub-region 0: [0x10020800:0x10020C00], Disabled
    Sub-region 1: [0x10020C00:0x10021000], Enabled
    Sub-region 2: [0x10021000:0x10021400], Enabled
    Sub-region 3: [0x10021400:0x10021800], Enabled
    Sub-region 4: [0x10021800:0x10021C00], Enabled
    Sub-region 5: [0x10021C00:0x10022000], Disabled
    Sub-region 6: [0x10022000:0x10022400], Disabled
    Sub-region 7: [0x10022400:0x10022800], Disabled
  Region 2: Unused
  Region 3: Unused
  Region 4: Unused
  Region 5: Unused
  Region 6: Unused
  Region 7: Unused

To debug, run `make debug RAM_START=0x20006000 FLASH_INIT=0x10020861`
in the app's folder and open the .lst file.
```

**Comment by bradjc** [comment]
```
---| Cortex-M Fault Status |---
No Cortex-M faults detected.
```

That is unexpected. Perhaps this has something to do with the cortex-m0 implementation? If there aren't any faults, what caused the app to fault?

**Comment by bradjc** [comment]
First attempt: I ran `make debug RAM_START=0x20004000 FLASH_INIT=0x10020071`. Relevant section of `cortex-m0.userland_debug.lst`:

```
1002038c <command>:
                         int arg1, int arg2) {
1002038c:	b510      	push	{r4, lr}
1002038e:	0004      	movs	r4, r0
10020390:	0008      	movs	r0, r1
10020392:	0011      	movs	r1, r2
10020394:	001a      	movs	r2, r3
  register uint32_t r3 __asm__ ("r3") = arg2;
10020396:	9b02      	ldr	r3, [sp, #8]
  __asm__ volatile (
10020398:	df02      	svc	2
  syscall_return_t rval = {rtype, {rv1, rv2, rv3}};
1002039a:	7020      	strb	r0, [r4, #0]
}
1002039c:	0020      	movs	r0, r4
  return rval;
1002039e:	6061      	str	r1, [r4, #4]
100203a0:	60a2      	str	r2, [r4, #8]
100203a2:	60e3      	str	r3, [r4, #12]
}
100203a4:	bd10      	pop	{r4, pc}
```

If the error is happening at address `0x100203a2`, then maybe some sort of stack corruption?

**Comment by hudson-ayers** [comment]
I also ran the command on libtock-c current master and got a different result

```
1002039c:	60a2      	str	r2, [r4, #8]
1002039e:	60e3      	str	r3, [r4, #12]
}
100203a0:	bd10      	pop	{r4, pc}

100203a2 <allow_readonly>:
allow_ro_return_t allow_readonly(uint32_t driver, uint32_t allow, const void* ptr, size_t size) {
100203a2:	b510      	push	{r4, lr}
100203a4:	0004      	movs	r4, r0
  register uint32_t r0 __asm__ ("r0")       = driver;
100203a6:	0008      	movs	r0, r1
  register uint32_t r1 __asm__ ("r1")       = allow;
100203a8:	0011      	movs	r1, r2
  register const void*    r2 __asm__ ("r2") = ptr;
100203aa:	001a      	movs	r2, r3
  register size_t r3 __asm__ ("r3")         = size;
100203ac:	9b02      	ldr	r3, [sp, #8]
  __asm__ volatile (
100203ae:	df04      	svc	4
  if (rtype == TOCK_SYSCALL_SUCCESS_U32_U32) {
100203b0:	2882      	cmp	r0, #130	; 0x82
```

**Comment by bradjc** [comment]
This is hard to debug externally.

My best thought so far is that since this is a cortex-m0 platform, and we 1) have different implementations for the functions in the arch crate than for m3/m4/etc, and 2) do not use the cortex-m0 arch crate regularly, that this stems from a bug in the arch/cortex-m0 crate. But I'm just guessing.

**Comment by hudson-ayers** [comment]
It seems like there may be two bugs this reveals, first whatever bug caused this fault, and second a bug where the cortex-m0 fault handler does not properly store the fault registers

**Comment by alexandruradovici** [comment]
I might be able to look into it in a few days.

**Comment by lschuermann** [comment]
@alexandruradovici Has this been fixed by the adjustments we made to the Cortex-M0+ context switch / trap handler assembly routines?

**Comment by alexandruradovici** [comment]
No sure, we need to test.

@JADarius can you test this now?

**Comment by JADarius** [comment]
I just ran the `rot13_client` application and everything seems to be in order.

**Comment by JADarius** [comment]
After trying to run it, I get the following panic:

```
RP2040 Revision 2 ASIC
Initialization compl
panicked at ./kernel/src/process_standard.rs:639:17:
                                                    Process org.tockos.examples.rot13 had a fault
	Kernel version release-2.0-5227-g4cd05d01f

---| Cortex-M Fault Status |---
No Cortex-M faults detected.

---| App Status |---
𝐀𝐩𝐩: org.tockos.examples.rot13   -   [Faulted]
 Events Queued: 0   Syscall Count: 8   Dropped Upcall Count: 0
 Restart Count: 0
 Last Syscall: Yield { which: 1, param_a: 0, param_b: 0 }
 Completion Code: None


 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x20006000═╪══════════════════════════════════════════╝
             │ Grant Ptrs       64
             │ Upcalls         320
             │ Process         768
  0x20005B80 ┼───────────────────────────────────────────
             │ ▼ Grant          76
  0x20005B34 ┼───────────────────────────────────────────
             │ Unused
  0x20004B24 ┼───────────────────────────────────────────
             │ ▲ Heap            0 |   4112               S
  0x20004B24 ┼─────────────────────────────────────────── R
             │ Data            804 |    804               A
  0x20004800 ┼─────────────────────────────────────────── M
             │ ▼ Stack         184 |   2048          
  0x20004748 ┼───────────────────────────────────────────
             │ Unused
  0x20004000 ┴───────────────────────────────────────────
             .....
  0x10042000 ┬─────────────────────────────────────────── F
             │ App Flash      8096                        L
  0x10040060 ┼─────────────────────────────────────────── A
             │ Protected        96                        S
  0x10040000 ┴─────────────────────────────────────────── H

  R0 : 0x00000001    R6 : 0x00000000
  R1 : 0x00000040    R7 : 0x00000000
  R2 : 0x20006940    R8 : 0x10040060
  R3 : 0x00000000    R10: 0x100405B4
  R4 : 0x00000000    R11: 0x00000000
  R5 : 0x20004800    R12: 0x2402E542
  R9 : 0x20004000 (Static Base Register)
  SP : 0x200047A0 (Process Stack Pointer)
  LR : 0x1004029B
  PC : 0x100400CA
 YPC : 0x1004029A

 APSR: N 0 Z 1 C 1 V 0 Q 0
       GE 0 0 0 0
 EPSR: ICI.IT 0x00
       ThumbBit true 

 Total number of grant regions defined: 8
  Grant  0 : --          Grant  3 : --          Grant  6 : --        
  Grant  1 : --          Grant  4 : --          Grant  7 0x10000: 0x20005b34
  Grant  2 : --          Grant  5 : --        

 Cortex-M MPU
  Region 0: [0x20004000:0x20005000], length: 4096 bytes; ReadWrite (0x3)
    Sub-region 0: [0x20004000:0x20004200], Enabled
    Sub-region 1: [0x20004200:0x20004400], Enabled
    Sub-region 2: [0x20004400:0x20004600], Enabled
    Sub-region 3: [0x20004600:0x20004800], Enabled
    Sub-region 4: [0x20004800:0x20004A00], Enabled
    Sub-region 5: [0x20004A00:0x20004C00], Enabled
    Sub-region 6: [0x20004C00:0x20004E00], Disabled
    Sub-region 7: [0x20004E00:0x20005000], Disabled
  Region 1: Unused
  Region 2: [0x10040000:0x10042000], length: 8192 bytes; UnprivilegedReadOnly (0x2)
    Sub-region 0: [0x10040000:0x10040400], Enabled
    Sub-region 1: [0x10040400:0x10040800], Enabled
    Sub-region 2: [0x10040800:0x10040C00], Enabled
    Sub-region 3: [0x10040C00:0x10041000], Enabled
    Sub-region 4: [0x10041000:0x10041400], Enabled
    Sub-region 5: [0x10041400:0x10041800], Enabled
    Sub-region 6: [0x10041800:0x10041C00], Enabled
    Sub-region 7: [0x10041C00:0x10042000], Enabled
  Region 3: Unused
  Region 4: Unused
  Region 5: Unused
  Region 6: Unused
  Region 7: Unused

To debug libtock-c apps, run
`make debug RAM_START=0x20004000 FLASH_INIT=0x10040089`
in the app's folder and open the .lst file.

𝐀𝐩𝐩: rot13_client   -   [Yielded]
 Events Queued: 0   Syscall Count: 10   Dropped Upcall Count: 0
 Restart Count: 0
 Last Syscall: Yield { which: 1, param_a: 0, param_b: 0 }
 Completion Code: None


 ╔═══════════╤══════════════════════════════════════════╗
 ║  Address  │ Region Name    Used | Allocated (bytes)  ║
 ╚0x20008000═╪══════════════════════════════════════════╝
             │ Grant Ptrs       64
             │ Upcalls         320
             │ Process         768
  0x20007B80 ┼───────────────────────────────────────────
             │ ▼ Grant          76
  0x20007B34 ┼───────────────────────────────────────────
             │ Unused
  0x20006C2C ┼───────────────────────────────────────────
             │ ▲ Heap            0 |   3848               S
  0x20006C2C ┼─────────────────────────────────────────── R
             │ Data           1068 |   1068               A
  0x20006800 ┼─────────────────────────────────────────── M
             │ ▼ Stack         152 |   2048          
  0x20006768 ┼───────────────────────────────────────────
             │ Unused
  0x20006000 ┴───────────────────────────────────────────
             .....
  0x10046000 ┬─────────────────────────────────────────── F
             │ App Flash     16304                        L
  0x10042050 ┼─────────────────────────────────────────── A
             │ Protected        80                        S
  0x10042000 ┴─────────────────────────────────────────── H

  R0 : 0x00000001    R6 : 0x00000000
  R1 : 0x00000000    R7 : 0x00000000
  R2 : 0x00000000    R8 : 0x20006800
  R3 : 0x20006800    R10: 0x20006940
  R4 : 0x00000000    R11: 0x80000000
  R5 : 0x20006800    R12: 0x25112AD7
  R9 : 0x20006980 (Static Base Register)
  SP : 0x200067A8 (Process Stack Pointer)
  LR : 0x20006800
  PC : 0x100422FA
 YPC : 0x100422FA

 APSR: N 0 Z 0 C 1 V 0 Q 0
       GE 0 0 0 0
 EPSR: ICI.IT 0x00
       ThumbBit true 

 Total number of grant regions defined: 8
  Grant  0 : --          Grant  3 : --          Grant  6 : --        
  Grant  1 : --          Grant  4 : --          Grant  7 0x10000: 0x20007b34
  Grant  2 : --          Grant  5 : --        

 Cortex-M MPU
  Region 0: [0x20006000:0x20007000], length: 4096 bytes; ReadWrite (0x3)
    Sub-region 0: [0x20006000:0x20006200], Enabled
    Sub-region 1: [0x20006200:0x20006400], Enabled
    Sub-region 2: [0x20006400:0x20006600], Enabled
    Sub-region 3: [0x20006600:0x20006800], Enabled
    Sub-region 4: [0x20006800:0x20006A00], Enabled
    Sub-region 5: [0x20006A00:0x20006C00], Enabled
    Sub-region 6: [0x20006C00:0x20006E00], Enabled
    Sub-region 7: [0x20006E00:0x20007000], Disabled
  Region 1: Unused
  Region 2: [0x10042000:0x10046000], length: 16384 bytes; UnprivilegedReadOnly (0x2)
    Sub-region 0: [0x10042000:0x10042800], Disabled
    Sub-region 1: [0x10042800:0x10043000], Enabled
    Sub-region 2: [0x10043000:0x10043800], Enabled
    Sub-region 3: [0x10043800:0x10044000], Disabled
    Sub-region 4: [0x10044000:0x10044800], Disabled
    Sub-region 5: [0x10044800:0x10045000], Disabled
    Sub-region 6: [0x10045000:0x10045800], Disabled
    Sub-region 7: [0x10045800:0x10046000], Disabled
  Region 3: Unused
  Region 4: Unused
  Region 5: Unused
  Region 6: Unused
  Region 7: Unused

To debug libtock-c apps, run
`make debug RAM_START=0x20006000 FLASH_INIT=0x10042079`
in the app's folder and open the .lst file.
```
